# Generated by Django 3.2.9 on 2021-12-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterField(
            model_name='country',
            name='people_count',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
